# Generated by Django 4.2.3 on 2023-08-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
    ]
