# Generated by Django 4.2.3 on 2023-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lga',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reg_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stage_origin',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
