# Generated by Django 4.2.3 on 2023-08-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_lga_profile_reg_no_profile_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='mick.png', upload_to='images'),
        ),
    ]
